<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	| 附加的编译类
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	| 这里你可以指定一个附加的类添加到"artisan optimize"命令生成的编译文件中，
	| 这些类应该是应用程序的每个请求会用到的类（否则会降低效率）。
	*/



);
